version: "3"

services:
  db:
    build: ./db
    environment:
      MYSQL_DATABASE: sls_db
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_HOST: localhost
    restart: always
    ports:
      - "3307:3306"

  node:
    build: .
    environment:
      MYSQL_DATABASE: sls_db
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_HOST: localhost
    ports:
      - "3001:3000"
    depends_on:
      - db
    restart: on-failure
