version: "3"

services:
  db:
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    restart: always
    ports:
      - "3307:3306"

  node:
    build: .
    env_file:
      - ./.env
    ports:
      - "3001:3000"
    depends_on:
      - db
    restart: on-failure
