version: "3"

services:
  db:
    build: ./db
    environment:
      - MYSQL_ROOT_PASSWORD="pwd123"
    restart: always
    ports:
      - "3307:3306"

  node:
    build: .
    env_file:
      - ./docker.env
    ports:
      - "3001:3000"
    links:
      - db:db
    restart: on-failure
